<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Find by email
     * 
     * @param string $email
     * 
     * @return null|AppBundle\Entity\User
     */
    public function findByEmail($email) {
        return $this->createQueryBuilder('u')
                ->where('u.email = :email')
                ->setParameter('email', $email)
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
    }
        
    /**
     * Gets count
     * 
     * @return int
     */
    public function count() {
        return $this->createQueryBuilder('u')->select('count(u.*)')->getQuery()->getSingleScalarResult();
    }
    
}
