<?php

namespace AppBundle\Repository;

/**
 * UserInTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInTrainingRepository extends \Doctrine\ORM\EntityRepository
{
}
